### ISSUE TITLE
mkdir for defaultTemplate is adding ':' in output path

### ISSUE THREAD

**Issue by misterbrownlee** [topcoat/topdoc-default-template#1]
HA! FOUND IT.  The additional delimiter parameter in path.resolve is putting ':' in the css output path (on OSX) for some reason.

If removed that, it seems to fix it.

**Comment by GarthDB** [comment]
Sweet - I'm on this, and I'm adding some basic tests to this repo.

**Comment by misterbrownlee** [comment]
ha ha you're faster than me... I had to fork and make a pull request, for some reason I couldn't pull request this directly and I didn't want to fix it straight on master.  Thanks for the fast turn around!
